version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: openstream
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    ports:
      - "9000:9000"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - minio
      - keycloak
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  admin:
    build: ./admin
    ports:
      - "3001:3001"
    depends_on:
      - server
